import {
  Shield,
  Clock,
  XCircle,
  FileX,
  Ban,
  type LucideIcon,
} from "lucide-react";

export interface RejectionCard {
  icon: LucideIcon;
  text: string;
  subtext: string;
  rotation: number;
  delay: number;
  top: string;
  left?: string;
  right?: string;
}

export const rejectionCards: RejectionCard[] = [
  // === LEFT FAR COLUMN (left: 2-7%) ===
  {
    icon: XCircle,
    text: "Başvurunuz değerlendirildi",
    subtext: "ama maalesef...",
    rotation: -12,
    delay: 0.8,
    top: "4%",
    left: "3%",
  },
  {
    icon: Ban,
    text: "Pozisyon dolduruldu",
    subtext: "aslında hiç açılmamıştı.",
    rotation: -5,
    delay: 1.6,
    top: "20%",
    left: "5%",
  },
  {
    icon: Shield,
    text: "Yapay zeka elemeyi geçti",
    subtext: "ama biz yine de reddettik.",
    rotation: -8,
    delay: 2.4,
    top: "38%",
    left: "3%",
  },
  {
    icon: Clock,
    text: "Şarj yüzdesi",
    subtext: "%12 şarjla mülakat mı?",
    rotation: 5,
    delay: 3.2,
    top: "63%",
    left: "4%",
  },
  {
    icon: FileX,
    text: "Kodu kopyaladınız",
    subtext: "StackOverflow kokusu aldık.",
    rotation: -5,
    delay: 4.0,
    top: "72%",
    left: "6%",
  },
  {
    icon: XCircle,
    text: "Klavye sesiniz",
    subtext: "Mekanik klavye? Çok gürültülü.",
    rotation: -10,
    delay: 4.8,
    top: "88%",
    left: "3%",
  },

  // === LEFT MID COLUMN (left: 13-19%) ===
  {
    icon: FileX,
    text: "Slack profili",
    subtext: "Emoji kullanmıyorsunuz.",
    rotation: 8,
    delay: 1.0,
    top: "6%",
    left: "16%",
  },
  {
    icon: XCircle,
    text: "Cevabınız çok hızlıydı",
    subtext: "robot olduğunuzdan şüpheliyiz.",
    rotation: -4,
    delay: 1.8,
    top: "24%",
    left: "14%",
  },
  {
    icon: Ban,
    text: "Junior arıyoruz",
    subtext: "ama 10 yıl tecrübe şart.",
    rotation: -7,
    delay: 2.6,
    top: "38%",
    left: "17%",
  },
  {
    icon: Shield,
    text: "Kedi tüyü",
    subtext: "CV'nizde tüy tespit edildi.",
    rotation: -10,
    delay: 3.4,
    top: "57%",
    left: "15%",
  },
  {
    icon: Clock,
    text: "Hobi fazlalığı",
    subtext: "İşe vakit kalmayacak gibi.",
    rotation: 6,
    delay: 4.2,
    top: "76%",
    left: "18%",
  },
  {
    icon: FileX,
    text: "Profil resminiz",
    subtext: "Vesikalık değil, çok mutlu.",
    rotation: 13,
    delay: 5.0,
    top: "83%",
    left: "14%",
  },

  // === TOP/BOTTOM CENTER FILLERS (avoiding main text area) ===
  {
    icon: XCircle,
    text: "Toplantı notu",
    subtext: "Comic Sans ile yazmışsınız.",
    rotation: -5,
    delay: 6.8,
    top: "15%",
    left: "42%",
  },
  {
    icon: Ban,
    text: "Zoom arka planı",
    subtext: "Bulanıklaştırma yok.",
    rotation: 8,
    delay: 7.2,
    top: "18%",
    right: "38%",
  },
  {
    icon: Clock,
    text: "Günaydın saati",
    subtext: "11:00'de günaydın denmez.",
    rotation: -3,
    delay: 7.6,
    top: "4%",
    left: "47%",
  },

  // === LEFT EDGE (left: 28-35%) — sparse, only top & bottom ===
  {
    icon: XCircle,
    text: "Email adresiniz",
    subtext: "çılgın_boy_99@... ciddiyetsiz.",
    rotation: 6,
    delay: 5.4,
    top: "2%",
    left: "32%",
  },
  {
    icon: XCircle,
    text: "Kültürel uyumsuzluk",
    subtext: "ofiste çok gülümsüyorsunuz.",
    rotation: 12,
    delay: 5.8,
    top: "86%",
    left: "30%",
  },

  // === RIGHT EDGE (right: 28-35%) — sparse, only top & bottom ===
  {
    icon: FileX,
    text: "Referansınız eksik",
    subtext: "kimseyi tanımıyorsunuz.",
    rotation: -15,
    delay: 6.0,
    top: "3%",
    right: "30%",
  },
  {
    icon: Shield,
    text: "Brokoli sevgisi",
    subtext: "Öğle yemeğinde yer misiniz?",
    rotation: 6,
    delay: 6.4,
    top: "70%",
    right: "25%",
  },

  // === RIGHT MID COLUMN (right: 13-19%) ===
  {
    icon: XCircle,
    text: "Masa düzeni",
    subtext: "Kablolar çok dağınık.",
    rotation: -15,
    delay: 1.2,
    top: "2%",
    right: "15%",
  },
  {
    icon: Ban,
    text: "İmza sirküleri",
    subtext: "Eğik çizgi açısı yanlış.",
    rotation: -6,
    delay: 2.0,
    top: "26%",
    right: "17%",
  },
  {
    icon: Clock,
    text: "Çay mı kahve mi?",
    subtext: "Çay dediniz, biz kahveciyiz.",
    rotation: -14,
    delay: 2.8,
    top: "44%",
    right: "14%",
  },
  {
    icon: XCircle,
    text: "Gömlek ütüsü",
    subtext: "Yaka hafif kırışık, elendiniz.",
    rotation: -5,
    delay: 3.6,
    top: "62%",
    right: "18%",
  },
  {
    icon: FileX,
    text: "Dark mode",
    subtext: "IDE'niz neden beyaz?",
    rotation: 10,
    delay: 4.4,
    top: "78%",
    right: "15%",
  },
  {
    icon: Shield,
    text: "Akraba bağı",
    subtext: "İçeride tanıdığınız yok.",
    rotation: 15,
    delay: 5.2,
    top: "93%",
    right: "16%",
  },

  // === RIGHT FAR COLUMN (right: 2-8%) ===
  {
    icon: FileX,
    text: "CV'niz incelendi",
    subtext: "tam 0.3 saniyede.",
    rotation: 8,
    delay: 0.9,
    top: "5%",
    right: "4%",
  },
  {
    icon: XCircle,
    text: "Mülakatınız tamamlandı",
    subtext: "başka bir adayda karar kıldık.",
    rotation: 10,
    delay: 1.7,
    top: "22%",
    right: "6%",
  },
  {
    icon: Ban,
    text: "Linkedın profiliniz",
    subtext: "maalesef çok renkli.",
    rotation: -5,
    delay: 2.5,
    top: "40%",
    right: "3%",
  },
  {
    icon: Clock,
    text: "Deneyiminiz fazla",
    subtext: "size bu maaşı veremeyiz.",
    rotation: 6,
    delay: 3.3,
    top: "57%",
    right: "5%",
  },
  {
    icon: Shield,
    text: "Font seçiminiz",
    subtext: "Inter mi? Çok ana akım.",
    rotation: 8,
    delay: 4.1,
    top: "74%",
    right: "7%",
  },
  {
    icon: XCircle,
    text: "Kahve tercihi",
    subtext: "Sütsüz mü? Çok sertsiniz.",
    rotation: -7,
    delay: 4.9,
    top: "90%",
    right: "4%",
  },

  // === EXTRA EDGE CARDS ===
  {
    icon: Ban,
    text: "Mülakat arka planı",
    subtext: "Kütüphane mi? Çok klişe.",
    rotation: -9,
    delay: 5.6,
    top: "14%",
    left: "7%",
  },
  {
    icon: Clock,
    text: "Excel becerisi",
    subtext: "VLOOKUP mı? XLOOKUP lütfen.",
    rotation: 7,
    delay: 6.2,
    top: "50%",
    right: "8%",
  },
  {
    icon: FileX,
    text: "Burç uyumsuzluğu",
    subtext: "Merkür retrosunda başvurdunuz.",
    rotation: -10,
    delay: 6.6,
    top: "32%",
    left: "6%",
  },
  {
    icon: XCircle,
    text: "Mülakatta çok su içtiniz",
    subtext: "fazla özgüvenli bulduk.",
    rotation: 15,
    delay: 7.0,
    top: "16%",
    right: "5%",
  },
  {
    icon: Shield,
    text: "Yetenek setiniz",
    subtext: "Docker biliyorsunuz, biz gemiciyiz.",
    rotation: 11,
    delay: 7.4,
    top: "66%",
    left: "16%",
  },
  {
    icon: Ban,
    text: "CV dosya adı",
    subtext: "cv_son_v12_final.pdf ? Hayır.",
    rotation: -8,
    delay: 7.8,
    top: "82%",
    right: "6%",
  },
  {
    icon: Clock,
    text: "Göz kırpma hızı",
    subtext: "Dakikada 12? Çok şüpheli.",
    rotation: -8,
    delay: 8.2,
    top: "48%",
    left: "15%",
  },
  {
    icon: FileX,
    text: "Github yeşilliği",
    subtext: "Gözlerimizi çok yordu.",
    rotation: 10,
    delay: 8.6,
    top: "68%",
    right: "16%",
  },
  {
    icon: Clock,
    text: "Bekleme listesi",
    subtext: "sıranız: 1.492.203",
    rotation: 5,
    delay: 9.0,
    top: "84%",
    left: "8%",
  },
  {
    icon: Clock,
    text: "İnternet hızınız",
    subtext: "Ping 15ms? Çok sabırsızsınız.",
    rotation: 4,
    delay: 9.4,
    top: "34%",
    right: "16%",
  },
  {
    icon: Ban,
    text: "İyi çalışmalar",
    subtext: "Maile 'Saygılarımla' yakışırdı.",
    rotation: 9,
    delay: 9.8,
    top: "52%",
    left: "5%",
  },
  {
    icon: Shield,
    text: "Sistem saati",
    subtext: "3 saniye geridesiniz.",
    rotation: -9,
    delay: 10.2,
    top: "10%",
    right: "17%",
  },
  {
    icon: XCircle,
    text: "Hava durumu",
    subtext: "Bugün hava çok kapalı.",
    rotation: 14,
    delay: 10.6,
    top: "92%",
    left: "17%",
  },
  {
    icon: Ban,
    text: "Işık hızı",
    subtext: "Kodunuz c'den yavaş.",
    rotation: -12,
    delay: 11.0,
    top: "96%",
    right: "8%",
  },

  // === MORE TOP FILLERS ===
  {
    icon: FileX,
    text: "Commit mesajı",
    subtext: "'fix' yazmışsınız, detay yok.",
    rotation: 6,
    delay: 11.4,
    top: "10%",
    right: "26%",
  },
  {
    icon: Shield,
    text: "Masaüstü",
    subtext: "Geri Dönüşüm Kutusu dolu.",
    rotation: -4,
    delay: 11.8,
    top: "12%",
    left: "28%",
  },
  {
    icon: XCircle,
    text: "Browser sekmesi",
    subtext: "100+ sekme açık, RAM ağlıyor.",
    rotation: 9,
    delay: 12.2,
    top: "24%",
    right: "28%",
  },

  // === MORE BOTTOM FILLERS ===
  {
    icon: XCircle,
    text: "Spotify listesi",
    subtext: "Arabesk dinliyorsunuz, biz Jazz severiz.",
    rotation: 8,
    delay: 12.4,
    top: "72%",
    left: "38%",
  },
  {
    icon: Ban,
    text: "Klavye kısayolu",
    subtext: "Ctrl+C kullanıyorsunuz, Vim şart.",
    rotation: -5,
    delay: 12.8,
    top: "75%",
    right: "35%",
  },
  {
    icon: Shield,
    text: "Mouse kullanımı",
    subtext: "Touchpad mi? Asla kabul edilemez.",
    rotation: 12,
    delay: 13.2,
    top: "80%",
    left: "45%",
  },
  {
    icon: Clock,
    text: "Ofis terliği",
    subtext: "Toplantıda terlik giydiniz.",
    rotation: -9,
    delay: 13.6,
    top: "78%",
    left: "28%",
  },
  {
    icon: FileX,
    text: "Su markası",
    subtext: "Musluk suyu içiyorsunuz.",
    rotation: 6,
    delay: 14.0,
    top: "82%",
    right: "26%",
  },

  {
    icon: Ban,
    text: "Tab vs Space",
    subtext: "Space kullandınız, bitti.",
    rotation: -7,
    delay: 12.6,
    top: "94%",
    left: "35%",
  },
  {
    icon: Clock,
    text: "Linkedin başlığı",
    subtext: "'Ninja' mı? Biz samuray arıyoruz.",
    rotation: 5,
    delay: 13.0,
    top: "91%",
    right: "32%",
  },
  {
    icon: FileX,
    text: "Kulaklık seçimi",
    subtext: "Kablolu mu? Yıl 2026.",
    rotation: -11,
    delay: 13.4,
    top: "97%",
    left: "28%",
  },
];
